# Generated by Django 5.1.7 on 2025-09-01 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=20)),
                ('mint_address', models.CharField(max_length=100, unique=True)),
                ('sol_amount', models.FloatField()),
                ('creator_address', models.CharField(max_length=100)),
            ],
        ),
    ]
