# Generated by Django 5.1.7 on 2025-09-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumplistener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='pump_fun_link',
            field=models.CharField(default='', max_length=200),
        ),
    ]
