# Generated by Django 5.1.7 on 2025-09-06 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumplistener', '0002_token_pump_fun_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='is_from_watchlist',
            field=models.BooleanField(default=False),
        ),
    ]
