# Generated by Django 5.1.7 on 2025-09-06 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumplistener', '0003_token_is_from_watchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField()),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='pumplistener.token')),
            ],
        ),
    ]
