# Generated by Django 5.1.7 on 2025-09-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumplistener', '0004_tokendatapoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='buy_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='current_holder_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='current_market_cap',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='highest_market_cap',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='initial_market_cap',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='token',
            name='sell_market_cap',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='sell_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
