# Generated by Django 5.1.7 on 2025-09-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumplistener', '0005_token_buy_timestamp_token_current_holder_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='peak_holder_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
