# Generated by Django 5.1.7 on 2025-10-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumplistener', '0006_token_peak_holder_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='buy_transaction_sig',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
